# Generated by Django 4.1.5 on 2023-03-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=20)),
            ],
        ),
    ]
